### PR TITLE
Raw data files for content

### PR DESCRIPTION
**Pull request by tejas-k3**
Work regarding updating the content
- Updated the Images across the Front page
- Updated the introduction, about us, services text
- Updated the footer

### CODE REVIEW

**Comment by tejas-k3** [comment]
### **Note!** 
The content files added as part of first commit will not be merged to mainline

**Review by siddhi-gh — CHANGES_REQUESTED** [review]
What happened to the `src` folder?
Why was `package.json` deleted?
Where are the UI component files?

Screenshot 2023-07-12 at 10 51 29 AM

### Package manager is removed, why?
```
siddhigupta@Siddhis-MacBook-Air aov-studios % yarn
yarn install v1.22.19
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
warning npm > @npmcli/ci-detect@2.0.0: this package has been deprecated, use `ci-info` instead
warning npm > libnpmexec > @npmcli/ci-detect@2.0.0: this package has been deprecated, use `ci-info` instead
warning npm > readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
warning npm > @npmcli/arborist > readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
warning npm > @npmcli/arborist > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
warning npm > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
warning npm > readdir-scoped-modules > debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Workspaces can only be enabled in private projects.
error An unexpected error occurred: "EACCES: permission denied, mkdir '/Users/siddhigupta/node_modules/ansi-regex'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/siddhigupta/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by tejas-k3** [comment]
This happened due to deploy and build commands mismatch, the commits related to this were reverted though last night. Maybe next attempt caused it. Will revert the particular commit.

**Comment by tejas-k3** [comment]
Preview :

https://github.com/GrowthVVork/aov-studios/assets/77725958/ef844ca4-ee7f-4881-81dd-8565c26d5e9a

**Comment by tejas-k3** [comment]
@siddhi-gh Please review & merge

**Review by siddhi-gh — COMMENTED** [review]
Send me the Hero picture in high quality.
@tejas-k3

**Review by siddhi-gh — COMMENTED** [review]
Not sure of the significance of numbers in Services section pictures:

Screenshot 2023-07-16 at 5 46 36 PM

**Comment by tejas-k3** [comment]
Those numbers are part of pictures affiliated with Architectural drawings

**Comment by siddhi-gh** [comment]
I meant the sequence- 1,2,5

**Comment by tejas-k3** [comment]
Hero image :
image

**Comment by tejas-k3** [comment]
1,2,5 seq is unsignificant for website work confirmed

**Review by siddhi-gh — APPROVED** [review]
The changes look good, Approved. 
There's still a lot of room for improvements wrt to image styles and screen responsive resolutions

Screenshot 2023-07-16 at 10 32 56 PM
Screenshot 2023-07-16 at 10 33 07 PM
Screenshot 2023-07-16 at 10 33 20 PM
Screenshot 2023-07-16 at 10 33 27 PM

**Comment by tejas-k3** [comment]
Yes, it'll be worked post this update.

**Pull request merged**
